[package]
name = "zbus_tester"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zbus_macros = { path = "../zbus/zbus_macros/" }
zbus = { path = "../zbus/zbus/" }
